/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiKontrol;
import database.islemler.HesapBilgileri;
import database.islemler.ParaCekme;
import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.ButtonAyarlari;
import gui.ayarlar.Dialogs;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.TextAyarlari;
import java.awt.Color;
import java.awt.Dialog;

/**
 *
 * @author sevinc
 */
public class ParaCekmeGui extends javax.swing.JFrame implements IDuzenleyici, IBilgiKontrol {

    /**
     * Creates new form ParaCekmeGui
     */
    private ParaCekme paraCekme = null;
    private int cekilecekMiktar = 0;
   

    public ParaCekmeGui() {
        initComponents();
        getEdits();
    }

    @Override
    public void getEdits() {
        this.setFocusable(true);
        this.setLocationRelativeTo(null);
        TextAyarlari.sadeceSayiGir(textMiktar);
        TextAyarlari.karakterSayiKontrol(textMiktar, 4);
        this.lblAdSoyad.setText(getHesapBilgileri().getAdSoyad());
        this.lblBakiye.setText(String.valueOf(getHesapBilgileri().getBakiye()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdSoyad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBakiye = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textMiktar = new javax.swing.JTextField();
        btnParaCek = new javax.swing.JButton();
        lblGeriIconTus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sweet Bank Para Çekme Ekranı");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lblAdSoyad.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAdSoyad.setForeground(new java.awt.Color(51, 51, 255));
        lblAdSoyad.setText("Sayın [Kullanıcı Adı Soyadı]");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tek seferde maksimum 5000 TL çekebilirsiniz!");

        lblBakiye.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBakiye.setText("[BAKİYE]");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Toplam Bakiyeniz :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Çekeceğiniz Miktar :");

        textMiktar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textMiktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMiktarActionPerformed(evt);
            }
        });
        textMiktar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textMiktarKeyReleased(evt);
            }
        });

        btnParaCek.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnParaCek.setText("Para Çek");
        btnParaCek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParaCek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnParaCekMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnParaCekMouseExited(evt);
            }
        });
        btnParaCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaCekActionPerformed(evt);
            }
        });

        lblGeriIconTus.setForeground(new java.awt.Color(255, 51, 51));
        lblGeriIconTus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/previousIcon.png"))); // NOI18N
        lblGeriIconTus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGeriIconTus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGeriIconTusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblAdSoyad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(btnParaCek)
                                    .addComponent(textMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBakiye))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblGeriIconTus)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblGeriIconTus)
                .addGap(31, 31, 31)
                .addComponent(lblAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBakiye)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addComponent(btnParaCek)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, lblBakiye, textMiktar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMiktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMiktarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMiktarActionPerformed

    private void btnParaCekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParaCekMouseEntered
        // TODO add your handling code here:
        ButtonAyarlari.setBg(btnParaCek, Color.red);
    }//GEN-LAST:event_btnParaCekMouseEntered

    private void btnParaCekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParaCekMouseExited
        // TODO add your handling code here:
        ButtonAyarlari.setOriginColor(btnParaCek);
    }//GEN-LAST:event_btnParaCekMouseExited

    private void lblGeriIconTusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeriIconTusMouseClicked
        // TODO add your handling code here:
        ActionAyarlari.setVisible(this, new HesapGui());
    }//GEN-LAST:event_lblGeriIconTusMouseClicked

    private void textMiktarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMiktarKeyReleased
        // TODO add your handling code here:
        cekilecekMiktar = TextAyarlari.setKeyReleased(textMiktar, 5000);
        textMiktar.setText(String.valueOf(cekilecekMiktar));

    }//GEN-LAST:event_textMiktarKeyReleased

    private void btnParaCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaCekActionPerformed
        // TODO add your handling code here:
        if (this.bilgilerGecerlimi()) {
            this.paraCek();
        } else {
            Dialogs.bosOlamazMesajGoster(this);
        }

    }//GEN-LAST:event_btnParaCekActionPerformed
    private void paraCek() {
       this.getParaCekme().setCekilecekMiktar(cekilecekMiktar);
       if(this.getParaCekme().paraCekildimi()){
           Dialogs.ozelMesajGoster(this, "Para çekme işlemi tamalandı.\n"
                   + "Çekilen miktar: " + this.cekilecekMiktar+ " TL.");
           
           ActionAyarlari.setVisible(this, new HesapGui());
       }else{
           Dialogs.ozelMesajGoster(this, "Bakiyeniz yeterli değildir.");
       }
       
       
    }

    public ParaCekme getParaCekme() {
        if (this.paraCekme == null) {
            paraCekme = new ParaCekme();
            
        }
        return paraCekme;
    }

    @Override
    public boolean bilgilerGecerlimi() {
        return !(this.textMiktar.getText().equals(""));
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        return HesapBilgileri.getInstance();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaCekmeGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParaCek;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdSoyad;
    private javax.swing.JLabel lblBakiye;
    private javax.swing.JLabel lblGeriIconTus;
    private javax.swing.JTextField textMiktar;
    // End of variables declaration//GEN-END:variables

}
